#!/bin/sh

picom --config $HOME/.config/picom/picom.conf &
set-wallpaper &
polybar -c $HOME/.config/polybar/polybar.ini -r &

export _JAVA_AWT_WM_NONREPARENTING=1

while type dwm >/dev/null ; do dwm && continue || break ; done
